---
functional:
  - Ползьзователь должен иметь возможность авторизации на сайте с помощью актуальных сервисов/платформ (например, Github)
  - Сайт должен поддерживать международный язык/иметь функцию выбора языка
  - Сайт должен иметь виртуального наставника/гида, который поможет разобраться в основных аспектах игры
  - Пользователь может сам создавать игровую сессию
  - Пользователь может производить настройку игровой сессии (выбор языка программирования/игровая задача/с кем играть/уровень сложности бота)
  - Пользователь может подключаться к уже созданным играм (к открытым комнатам)
  - Пользователь может наблюдать за уже запущенными сессиями
  - Пользователь может воспользоваться чатом во время игры 
  - Пользователь может проверить свое решение на корректность, запустив тесты 
  - Пользователь может сменить язык программирования в ходе запущенной сессии
  - Пользователь может может завершить игру (поднять флаг) в любой момент
  - Пользователь может может продолжить игру, если его ответ (после поднятого флага) оказался неверным, при условии, что оппонент еще не завершил свое задание
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть понятным и простым в использовании 
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Сайт и его материалы не должны оскорблять чувства пользователей и навязывать свои убеждения (заниматься пропагандой)
  - Сайт не должен использовататься в качестве инструмента рекламы и продвижения нелегальных услуг, согласно закону
